services:
  db:
    image: postgres:15
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-churn_db}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    build: .
    command: sh -c "alembic upgrade head && streamlit run /app/streamlit_app.py --server.port 8501 --server.address 0.0.0.0"
    volumes:
      - .:/app
    ports:
      - '8501:8501'
    env_file: .env
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - MLFLOW_EXPERIMENT_NAME=${MLFLOW_EXPERIMENT_NAME}

      - ENABLE_RUNTIME_DB_BOOTSTRAP=false
    depends_on:
      - db
      - mlflow

  mlflow:
    build:
      context: .
      dockerfile: Dockerfile
    command: >-
      mlflow server
      --backend-store-uri sqlite:////mlflow/mlflow.db
      --serve-artifacts
      --artifacts-destination /mlflow/artifacts
      --host 0.0.0.0
      --port 5000
      --allowed-hosts=*
      --cors-allowed-origins=*
    environment:
      - MLFLOW_ARTIFACT_URI=file:///mlflow/artifacts
    volumes:
      - mlflow_data:/mlflow
    ports:
      - '5000:5000'

volumes:
  postgres_data:
  mlflow_data:
